services:
  main:
    build: 
      context: .
      dockerfile: Dockerfile  
    container_name: node_project
    ports:
      - "3000:3000"
    volumes:
    - ./:/app
    - /app/node_modules
    - /app/.next
      